### PR TITLE
Updates to travis publishing

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
this brings the admin directory in line with the other modules, we still had an old version here

**Comment by lrytz** [comment]
Build failed because https://github.com/scala/bug/issues/10281 and because the latest version of the sbt-scala-modules plugin actually succeeds to enable `-Xlint` (before it didn't due to a misconfiguration)

**Comment by lrytz** [comment]
should be ready now @danslapman

**Comment by danslapman** [comment]
Thanks @lrytz

**Pull request merged**
