### PR TITLE
[WIP] release for Scala 2.12.1

### PR DESCRIPTION
**Pull request by danslapman**
There is a need of updating auto-publish machinery. One possible way is described here: https://github.com/scala/sbt-scala-modules/issues/12

### CODE REVIEW

**Comment by dotta** [comment]
Would be great to have this merged and released :)

**Comment by TiarkRompf** [comment]
👍

**Comment by dotta** [comment]
ping

**Comment by danslapman** [comment]
@SethTisue I backported @lrytz's admin.sh improvements. take a look, if all is fine I will merge this & build artifacts for 2.11.11, 2.12.1 & 2.12.2

**Comment by SethTisue** [comment]
it looks like this PR doesn't have `crossScalaVersions` fully updated yet to include the new Scala versions.

is build.sh really the only file needing updating, didn't Lukas also update a readme and perhaps other files?

otherwise LGTM, but I'm unlikely to spot script problems by eyeball. since releases are staged on Sonatype before they're published, I'd suggest just going for it, and if the contents of the staging repo seem to be correct, then it's good and we can hit "release", else drop and try again.

note that at the same time you're doing this, you could consider also attempting to publish for 2.13.0-M1 — might as well start shaking out 2.13 problems early. but if you're pressed for time, it could wait for a future round.

**Comment by danslapman** [comment]
I did not fully updated `crossScalaVersions` because we need 3 tags to release 3 artifact and I intended to do this by 3 separate commits.
To be honest, I didn't checked out 2.13.0-M1 yet, but it's definitely a good point to add it to cross build.
Merging this to take a try with building against 2.12.1

**Comment by SethTisue** [comment]
> I didn't checked out 2.13.0-M1 yet, but it's definitely a good point to add it to cross build

tracking as #30

**Comment by danslapman** [comment]
@SethTisue thanks!

**Comment by lrytz** [comment]
I realized that I'll need to add one more dimension to these kind of tags, the java version. We typically want to build 2.11 binaries on Java 6, 2.12 binaries on Java 8. WIP here: https://github.com/scala/sbt-scala-modules/pull/18. I'll also make a PR here once things are in place. If the current state works for the releases you want to do you can go ahead of course.

**Pull request merged**
