### PR TITLE
Add deploy version filter to build.sh

### PR DESCRIPTION
**Pull request by danslapman**
Extra condition to disable double artifact publishing and travis crashes

### CODE REVIEW

**Comment by lrytz** [comment]
This should not be necessary, the sbt plugin will make sure that the sbt build exists when a release build is running and the `UseForPublishing` flag is false (https://github.com/scala/scala-continuations/blob/master/build.sbt#L10-L20)

**Comment by lrytz** [comment]
https://github.com/scala/sbt-scala-modules/blob/master/src/main/scala/ScalaModulePlugin.scala#L30-L39

**Comment by danslapman** [comment]
@lrytz I added this because when You push a tag crossScalaVersions are overriden by build.sh. This causes crash in travis because both jdk6 & jdk8 are used un travis: https://github.com/scala/scala-continuations/blob/master/.travis.yml#L17-L18

**Comment by danslapman** [comment]
@lrytz problem's here https://travis-ci.org/scala/scala-continuations/builds/224276366

**Comment by lrytz** [comment]
> @lrytz I added this because when You push a tag crossScalaVersions are overriden by build.sh. This causes crash in travis because both jdk6 & jdk8 are used un travis: https://github.com/scala/scala-continuations/blob/master/.travis.yml#L17-L18

yes, that part i still need to fix, i'm aware of it. instead of overwriting `crossScalaVersions`, the script should overwrite `scalaVersionsByJvm`. But we need to also know the JVM version, so the tags need another `#N`. I'm working on this, I'll also push it here once it's ready.

**Comment by danslapman** [comment]
@lrytz I think adding another `#N` is more ugly than filtering idk version somehow

**Comment by danslapman** [comment]
2.11.x releases always need to be published under jdk6 to ensure compatibility & 2.12.x releases simply can't be built on jdk6

**Comment by lrytz** [comment]
Agree it's more ugly, but also more future-proof. We might not always have a clear distinction, maybe you want to build something on JDK 9 at some point. Anyway it's not a feature for users, just for the maintainers, and it's not that hard to understand either.

**Comment by danslapman** [comment]
@lrytz sounds reasonable

**Pull request merged**
