### PR TITLE
Test against Scala 2.12.0-M5

### PR DESCRIPTION
**Pull request by danslapman**
This PR updates scala 2.12 series version to 2.12.0-M5 in Travis

### CODE REVIEW

**Comment by danslapman** [comment]
@adriaanm this PR updates scala to 2.12.0-M5, can You please publish the appropriate artifact?

**Comment by SethTisue** [comment]
fixes #14

**Comment by SethTisue** [comment]
I hope to get to this this week. (clearing big backlog after returning from leave)

**Comment by danslapman** [comment]
@SethTisue thank You!

**Pull request merged**
